// Dino cries, generated by the synthesizer (src/audio/synth.js, one voice per species
// family). Each cry is rendered once into a sound buffer, then replayed with variations:
// mood (attack, hurt, fainting…), distance, left/right position and cave echo.

import { scheduleCry } from "../../../src/audio/cry.js";
import { audioContext, masterOut, echoInput } from "./sounds.js";

const RENDER_SECONDS = 4;
const SILENCE = 0.003;
const cache = new Map(); // cry key -> Promise<AudioBuffer | null>

// rate: pitch and speed; gain: loudness; maxLen: cut after (s); slide: pitch drops to
// rate × slide by the end; wobble: shaky pitch.
const MOODS = {
  normal: { rate: 1, gain: 1 },
  happy: { rate: 1.18, gain: 0.85, maxLen: 1 },
  attack: { rate: 1.1, gain: 0.9, maxLen: 0.75 },
  roar: { rate: 0.94, gain: 1.25 },
  hurt: { rate: 0.8, gain: 0.95, maxLen: 0.5, wobble: true },
  weak: { rate: 0.86, gain: 0.6, wobble: true },
  faint: { rate: 0.78, gain: 1, slide: 0.5 },
};

// The parts that shape a cry (see scheduleCry): the rest of the body does not matter.
const keyOf = (build) => [build.head, build.teeth, build.tail, build.backLegs, build.back].join("-");

function render(build) {
  const key = keyOf(build);
  if (!cache.has(key)) cache.set(key, renderOffline(build).catch(() => null));
  return cache.get(key);
}

async function renderOffline(build) {
  const live = audioContext();
  const rate = live?.sampleRate || 44100;
  const OAC = window.OfflineAudioContext || window.webkitOfflineAudioContext;
  if (!OAC) return null;
  const off = new OAC(2, Math.round(rate * RENDER_SECONDS), rate);
  scheduleCry(off, off.destination, build);
  return normalize(trimSilence(await off.startRendering()));
}

// The synth voices differ a lot in loudness (a hiss is far quieter than a roar):
// bring every cry to the same peak level.
const TARGET_PEAK = 0.8;
const MAX_BOOST = 12;
function normalize(buf) {
  let peak = 0;
  for (let c = 0; c < buf.numberOfChannels; c++) for (const v of buf.getChannelData(c)) peak = Math.max(peak, Math.abs(v));
  if (!peak) return buf;
  const k = Math.min(MAX_BOOST, TARGET_PEAK / peak);
  for (let c = 0; c < buf.numberOfChannels; c++) { const d = buf.getChannelData(c); for (let i = 0; i < d.length; i++) d[i] *= k; }
  return buf;
}

// Drops the silent tail so short moods and cut-offs line up with the actual sound.
function trimSilence(buf) {
  const data = buf.getChannelData(0);
  let end = data.length - 1;
  while (end > 0 && Math.abs(data[end]) < SILENCE) end--;
  const len = Math.min(data.length, end + Math.round(buf.sampleRate * 0.05));
  const out = new AudioBuffer({ numberOfChannels: buf.numberOfChannels, length: Math.max(1, len), sampleRate: buf.sampleRate });
  for (let c = 0; c < buf.numberOfChannels; c++) out.copyToChannel(buf.getChannelData(c).subarray(0, len), c);
  return out;
}

/** Renders a dino's cry in advance, so its first play has no delay. */
export function preloadCry(d) {
  if (audioContext()) render(d.build || d);
}

/**
 * Plays the cry of dino `d` (or a build).
 * opts: mood (see MOODS), volume 0..1, pan -1..1, distance 0 (close) .. 1 (far, muffled), echo 0..1
 */
export async function playCry(d, { mood = "normal", volume = 1, pan = 0, distance = 0, echo = 0 } = {}) {
  const ctx = audioContext();
  if (!ctx || ctx.state !== "running") return;
  const buf = await render(d.build || d);
  if (!buf) return;
  const m = MOODS[mood] || MOODS.normal;
  const t = ctx.currentTime + 0.01;
  const rate = m.rate * (1 + (Math.random() * 2 - 1) * 0.04);
  const length = Math.min(buf.duration / rate, m.maxLen ?? Infinity);

  const src = ctx.createBufferSource();
  src.buffer = buf;
  src.playbackRate.setValueAtTime(rate, t);
  if (m.slide) src.playbackRate.linearRampToValueAtTime(rate * m.slide, t + length);
  if (m.wobble) {
    const lfo = ctx.createOscillator(), depth = ctx.createGain();
    lfo.frequency.value = 9;
    depth.gain.value = rate * 0.08;
    lfo.connect(depth).connect(src.playbackRate);
    lfo.start(t); lfo.stop(t + length + 0.1);
  }

  const gain = ctx.createGain();
  const level = Math.max(0, Math.min(1.5, volume * m.gain));
  gain.gain.setValueAtTime(level, t);
  gain.gain.setValueAtTime(level, t + Math.max(0, length - 0.12));
  gain.gain.linearRampToValueAtTime(0, t + length);

  // Far away: quieter highs, like through the trees.
  const tone = ctx.createBiquadFilter();
  tone.type = "lowpass";
  tone.frequency.value = 9000 - Math.min(1, distance) * 7800;
  const panner = ctx.createStereoPanner ? ctx.createStereoPanner() : null;
  if (panner) panner.pan.value = Math.max(-1, Math.min(1, pan));

  let out = src.connect(tone).connect(gain);
  if (panner) out = out.connect(panner);
  out.connect(masterOut());
  if (echo > 0) {
    const send = ctx.createGain();
    send.gain.value = echo;
    out.connect(send).connect(echoInput());
  }
  src.start(t);
  src.stop(t + length + 0.05);
}
