extends RefCounted
## The joins between the outdoor zones (Forêt, Marais, Désert, Côte, Monts): a picture from each side, standing by the edge
## (the camera looks north), to see what changes at each one (ground, trails, plants, relief).
## No scene played. godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/carte_transitions_2.gd

const STEPS := [
	[0.8, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "maia_enfuie", "roc_parti_vu", "monts_ouverts", "monts_arrivee", "bertille_vue", "glacier_arrivee", "camp_arrive"]],
	[0.85, "talk", true],
	[0.9, "weather", &"clear"],
	[1.00, "zone", &"foret"],
	[3.60, "weather", &"clear"],
	[3.61, "clock", 11.0],
	[3.62, "calm", 900.0],
	[3.63, "camera_distance", 16.0],
	[3.80, "tp", Vector2(4.5, 12)],
	[3.90, "face", Vector2(-1, 0)],
	[6.00, "shot", "05a_foret_vers_marais"],
	[6.20, "zone", &"marais"],
	[8.80, "weather", &"clear"],
	[8.81, "clock", 11.0],
	[8.82, "calm", 900.0],
	[9.00, "tp", Vector2(115.5, 70)],
	[9.10, "face", Vector2(1, 0)],
	[11.20, "shot", "05b_marais_vers_foret"],
	[11.40, "tp", Vector2(86, 4)],
	[11.50, "face", Vector2(0, -1)],
	[13.60, "shot", "06a_marais_vers_desert"],
	[13.80, "zone", &"desert"],
	[16.40, "weather", &"clear"],
	[16.41, "clock", 11.0],
	[16.42, "calm", 900.0],
	[16.60, "tp", Vector2(102, 95)],
	[16.70, "face", Vector2(0, 1)],
	[18.80, "shot", "06b_desert_vers_marais"],
	[19.00, "tp", Vector2(100, 4)],
	[19.10, "face", Vector2(0, -1)],
	[21.20, "shot", "07a_desert_vers_cote"],
	[21.40, "zone", &"cote"],
	[24.00, "weather", &"clear"],
	[24.01, "clock", 11.0],
	[24.02, "calm", 900.0],
	[24.20, "tp", Vector2(20, 95)],
	[24.30, "face", Vector2(0, 1)],
	[26.40, "shot", "07b_cote_vers_desert"],
	[26.60, "tp", Vector2(123.5, 58)],
	[26.70, "face", Vector2(1, 0)],
	[28.80, "shot", "08a_cote_vers_monts"],
	[29.00, "zone", &"monts"],
	[31.60, "weather", &"clear"],
	[31.61, "clock", 11.0],
	[31.62, "calm", 900.0],
	[31.80, "tp", Vector2(4.5, 30.5)],
	[31.90, "face", Vector2(-1, 0)],
	[34.00, "shot", "08b_monts_vers_cote"],
	[34.20, "state", null],
]
