extends RefCounted
## The joins between the outdoor zones (Port-Ambre, Havre-Doré, Plaines, Forêt, Camp de l'Ombre): a picture from each side, standing by the edge
## (the camera looks north), to see what changes at each one (ground, trails, plants, relief).
## No scene played. godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/carte_transitions.gd

const STEPS := [
	[0.8, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "maia_enfuie", "roc_parti_vu", "monts_ouverts", "monts_arrivee", "bertille_vue", "glacier_arrivee", "camp_arrive"]],
	[0.85, "talk", true],
	[0.9, "weather", &"clear"],
	[1.00, "zone", &"port_ambre"],
	[3.60, "weather", &"clear"],
	[3.61, "clock", 11.0],
	[3.62, "calm", 900.0],
	[3.63, "camera_distance", 16.0],
	[3.80, "tp", Vector2(36.5, 10.5)],
	[3.90, "face", Vector2(1, 0)],
	[6.00, "shot", "01a_port_vers_havre"],
	[6.20, "zone", &"havre_dore"],
	[8.80, "weather", &"clear"],
	[8.81, "clock", 11.0],
	[8.82, "calm", 900.0],
	[9.00, "tp", Vector2(3.5, 10.5)],
	[9.10, "face", Vector2(-1, 0)],
	[11.20, "shot", "01b_havre_vers_port"],
	[11.40, "zone", &"port_ambre"],
	[14.00, "weather", &"clear"],
	[14.01, "clock", 11.0],
	[14.02, "calm", 900.0],
	[14.20, "tp", Vector2(17, 3.5)],
	[14.30, "face", Vector2(0, -1)],
	[16.40, "shot", "02a_port_vers_plaines"],
	[16.60, "zone", &"plaines"],
	[19.20, "weather", &"clear"],
	[19.21, "clock", 11.0],
	[19.22, "calm", 900.0],
	[19.40, "tp", Vector2(60, 85)],
	[19.50, "face", Vector2(0, 1)],
	[21.60, "shot", "02b_plaines_vers_port"],
	[21.80, "tp", Vector2(4.5, 52)],
	[21.90, "face", Vector2(-1, 0)],
	[24.00, "shot", "03a_plaines_vers_foret"],
	[24.20, "zone", &"foret"],
	[26.80, "weather", &"clear"],
	[26.81, "clock", 11.0],
	[26.82, "calm", 900.0],
	[27.00, "tp", Vector2(125.5, 52)],
	[27.10, "face", Vector2(1, 0)],
	[29.20, "shot", "03b_foret_vers_plaines"],
	[29.40, "zone", &"camp_ombre"],
	[32.00, "weather", &"clear"],
	[32.01, "clock", 11.0],
	[32.02, "calm", 900.0],
	[32.20, "tp", Vector2(36.5, 14)],
	[32.30, "face", Vector2(1, 0)],
	[34.40, "shot", "04a_camp_vers_foret"],
	[34.60, "zone", &"foret"],
	[37.20, "weather", &"clear"],
	[37.21, "clock", 11.0],
	[37.22, "calm", 900.0],
	[37.40, "tp", Vector2(12, 42)],
	[37.50, "face", Vector2(0, -1)],
	[39.60, "shot", "04b_foret_vers_camp"],
	[39.80, "state", null],
]
