extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): vérification pendant les répliques : le Titan descend, renifle, rugit ; (combat sauté) l'autel, le Sceau, le 4e Cœur, le regard vers le ciel.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_titan_verif.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee", "bertille_vue", "glacier_arrivee", "mur_glace_1_brise", "mur_glace_2_brise", "grottes_glace_arrivee", "suie_monts_vue", "suie_monts_battue", "suie_monts_partie", "suie_indice", "dormeurs_reveilles", "blizzard_col", "roc_col_vu", "roc_innocente", "porte_givre_vue", "sanctuaire_givre_ouvert"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 35],
	[0.92, "item", ["piece", 450]],
	[0.94, "item", ["manteau_duvet", 1]],
	[0.96, "clock", 11],
	[0.98, "dlog", true],
	[1.00, "demo", true],
	[1.02, "no_help", null],
	[1.04, "auto", false],
	[1.06, "fast_battles", true],
	[1.36, "zone", &"sanctuaire_givre"],
	[3.16, "calm", 900],
	[4.76, "shot", "titan_verif_00_arrivee"],
	[6.36, "press", "interact"],
	[7.96, "shot", "titan_verif_01_arrivee"],
	[9.56, "press", "interact"],
	[11.16, "shot", "titan_verif_02_arrivee"],
	[12.76, "press", "interact"],
	[14.36, "shot", "titan_verif_03_arrivee"],
	[15.96, "press", "interact"],
	[17.56, "shot", "titan_verif_04_arrivee"],
	[19.16, "press", "interact"],
	[20.76, "shot", "titan_verif_05_arrivee"],
	[22.36, "press", "interact"],
	[23.96, "shot", "titan_verif_06_arrivee"],
	[25.56, "press", "interact"],
	[25.86, "calm", 900],
	[25.91, "tp", Vector2(16, 12.5)],
	[26.11, "wait_idle", [0.3, 60]],
	[26.21, "face", Vector2(0, -1)],
	[26.51, "interact_now", null],
	[28.11, "shot", "titan_verif_07_renifle"],
	[29.71, "press", "interact"],
	[31.31, "shot", "titan_verif_08_renifle"],
	[32.91, "press", "interact"],
	[34.51, "shot", "titan_verif_09_renifle"],
	[36.11, "press", "interact"],
	[37.71, "shot", "titan_verif_10_renifle"],
	[39.31, "press", "interact"],
	[40.91, "shot", "titan_verif_11_renifle"],
	[42.51, "press", "interact"],
	[44.11, "shot", "titan_verif_12_renifle"],
	[45.71, "press", "interact"],
	[47.31, "shot", "titan_verif_13_renifle"],
	[48.91, "press", "interact"],
	[48.96, "pick", 1],
	[50.56, "shot", "titan_verif_14_pas_encore"],
	[52.16, "press", "interact"],
	[52.46, "flags", ["titan_battu"]],
	[52.76, "static", ["res://story/monts_sanctuaire.gd", "_opens_altar", "@Titan"]],
	[54.36, "shot", "titan_verif_15_autel"],
	[55.96, "press", "interact"],
	[57.56, "shot", "titan_verif_16_autel"],
	[59.16, "press", "interact"],
	[60.76, "shot", "titan_verif_17_autel"],
	[62.36, "press", "interact"],
	[63.96, "shot", "titan_verif_18_autel"],
	[65.56, "press", "interact"],
	[67.16, "shot", "titan_verif_19_autel"],
	[68.76, "press", "interact"],
	[70.36, "shot", "titan_verif_20_autel"],
	[71.96, "press", "interact"],
	[73.56, "shot", "titan_verif_21_autel"],
	[75.16, "press", "interact"],
	[76.76, "shot", "titan_verif_22_autel"],
	[78.36, "press", "interact"],
	[79.96, "shot", "titan_verif_23_autel"],
	[81.56, "press", "interact"],
	[83.16, "shot", "titan_verif_24_autel"],
	[84.76, "press", "interact"],
	[86.36, "shot", "titan_verif_25_autel"],
	[87.96, "press", "interact"],
	[89.56, "shot", "titan_verif_26_autel"],
	[91.16, "press", "interact"],
	[92.76, "shot", "titan_verif_27_autel"],
	[94.36, "press", "interact"],
	[95.96, "shot", "titan_verif_28_autel"],
	[97.56, "press", "interact"],
	[97.96, "state", null],
	[98.06, "party", null],
	[98.16, "tracker", null],
]
