extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): Bertille compte ses troupeaux, reconnaît les yeux d'Hélène, la dame en gris, Grelot disparu, les murs de glace.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_bertille.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 31],
	[0.92, "item", ["piece", 450]],
	[0.94, "item", ["manteau_duvet", 1]],
	[0.96, "clock", 11],
	[0.98, "dlog", true],
	[1.00, "demo", true],
	[1.02, "no_help", null],
	[1.04, "auto", true],
	[1.06, "fast_battles", true],
	[1.36, "zone", &"monts"],
	[3.16, "calm", 900],
	[3.46, "calm", 900],
	[3.51, "tp", Vector2(22.5, 59.4)],
	[3.71, "wait_idle", [0.3, 60]],
	[3.81, "face", Vector2(0, -1)],
	[4.11, "interact_now", null],
	[5.41, "shot", "bertille_00_rencontre"],
	[6.71, "shot", "bertille_01_rencontre"],
	[8.01, "shot", "bertille_02_rencontre"],
	[9.31, "shot", "bertille_03_rencontre"],
	[10.61, "shot", "bertille_04_rencontre"],
	[11.91, "shot", "bertille_05_rencontre"],
	[13.21, "shot", "bertille_06_rencontre"],
	[14.51, "shot", "bertille_07_rencontre"],
	[15.81, "shot", "bertille_08_rencontre"],
	[17.11, "shot", "bertille_09_rencontre"],
	[18.41, "shot", "bertille_10_rencontre"],
	[19.71, "shot", "bertille_11_rencontre"],
	[19.91, "wait_idle", [2, 90]],
	[20.21, "shot", "bertille_12_fin"],
	[20.61, "state", null],
	[20.71, "party", null],
	[20.81, "tracker", null],
]
