extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): les grottes de glace : la salle bleue, la réserve, Dame Suie, le combat (Aconit apaisé), son doute, l'indice, son départ, les dormeurs réveillés.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_suie.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee", "bertille_vue", "glacier_arrivee", "mur_glace_1_brise", "mur_glace_2_brise"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 33],
	[0.92, "item", ["piece", 450]],
	[0.94, "item", ["manteau_duvet", 1]],
	[0.96, "clock", 11],
	[0.98, "dlog", true],
	[1.00, "demo", true],
	[1.02, "no_help", null],
	[1.04, "auto", true],
	[1.06, "fast_battles", true],
	[1.36, "zone", &"grottes_glace"],
	[3.16, "calm", 900],
	[4.36, "shot", "suie_00_entree"],
	[5.56, "shot", "suie_01_entree"],
	[6.76, "shot", "suie_02_entree"],
	[7.96, "shot", "suie_03_entree"],
	[8.16, "wait_idle", [1, 40]],
	[8.46, "calm", 900],
	[8.51, "tp", Vector2(22, 13)],
	[8.71, "wait_idle", [0.3, 60]],
	[8.91, "hold", "move_up"],
	[9.41, "hold", ""],
	[10.91, "shot", "suie_04_reserve"],
	[12.41, "shot", "suie_05_reserve"],
	[13.91, "shot", "suie_06_reserve"],
	[15.41, "shot", "suie_07_reserve"],
	[16.91, "shot", "suie_08_reserve"],
	[18.41, "shot", "suie_09_reserve"],
	[19.91, "shot", "suie_10_reserve"],
	[21.41, "shot", "suie_11_reserve"],
	[22.91, "shot", "suie_12_reserve"],
	[24.41, "shot", "suie_13_reserve"],
	[24.61, "wait_idle", [3, 240]],
	[24.91, "shot", "suie_14_apres_suie"],
	[25.21, "calm", 900],
	[25.26, "tp", Vector2(15, 6.4)],
	[25.46, "wait_idle", [0.3, 60]],
	[25.56, "face", Vector2(0, -1)],
	[25.86, "interact_now", null],
	[27.16, "shot", "suie_15_dormeurs"],
	[28.46, "shot", "suie_16_dormeurs"],
	[29.76, "shot", "suie_17_dormeurs"],
	[31.06, "shot", "suie_18_dormeurs"],
	[32.36, "shot", "suie_19_dormeurs"],
	[33.66, "shot", "suie_20_dormeurs"],
	[34.96, "shot", "suie_21_dormeurs"],
	[36.26, "shot", "suie_22_dormeurs"],
	[36.46, "wait_idle", [2, 90]],
	[36.76, "shot", "suie_23_fin"],
	[37.16, "state", null],
	[37.26, "party", null],
	[37.36, "tracker", null],
]
