extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): la sortie des Monts sans manteau (ce qui manque), Joss et ses manteaux (achat), la sortie ouverte, l'arrivée aux Monts.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_manteau.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "joss_apres_coeur", "joss_ferreol"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 31],
	[0.92, "item", ["piece", 450]],
	[0.94, "clock", 11],
	[0.96, "dlog", true],
	[0.98, "demo", true],
	[1.00, "no_help", null],
	[1.02, "auto", true],
	[1.04, "fast_battles", true],
	[1.34, "zone", &"cote"],
	[3.14, "calm", 900],
	[3.44, "calm", 900],
	[3.49, "tp", Vector2(126.2, 58)],
	[3.69, "wait_idle", [0.3, 60]],
	[3.89, "hold", "move_right"],
	[5.09, "hold", ""],
	[5.29, "wait_idle", [1, 20]],
	[5.59, "shot", "manteau_00_bloque"],
	[5.89, "calm", 900],
	[5.94, "tp", Vector2(60, 57.95)],
	[6.14, "wait_idle", [0.3, 60]],
	[6.24, "face", Vector2(0, -1)],
	[6.54, "interact_now", null],
	[7.74, "shot", "manteau_01_joss"],
	[8.94, "shot", "manteau_02_joss"],
	[10.14, "shot", "manteau_03_joss"],
	[10.19, "pick", 0],
	[10.39, "wait_idle", [1, 30]],
	[10.89, "shop_buy", "manteau_duvet"],
	[11.19, "shot", "manteau_04_boutique"],
	[11.69, "press", "cancel"],
	[11.89, "wait_idle", [1, 20]],
	[12.19, "shot", "manteau_05_apres"],
	[12.39, "coins", null],
	[12.69, "calm", 900],
	[12.74, "tp", Vector2(126.2, 58)],
	[12.94, "wait_idle", [0.3, 60]],
	[13.14, "hold", "move_right"],
	[14.64, "hold", ""],
	[15.84, "shot", "manteau_06_arrivee"],
	[17.04, "shot", "manteau_07_arrivee"],
	[18.24, "shot", "manteau_08_arrivee"],
	[19.44, "shot", "manteau_09_arrivee"],
	[20.64, "shot", "manteau_10_arrivee"],
	[21.84, "shot", "manteau_11_arrivee"],
	[23.04, "shot", "manteau_12_arrivee"],
	[24.24, "shot", "manteau_13_arrivee"],
	[24.44, "wait_idle", [2, 90]],
	[24.74, "shot", "manteau_14_fin"],
	[25.14, "state", null],
	[25.24, "party", null],
	[25.34, "tracker", null],
]
