extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): Grelot fonce sur le mur de glace, BONG ; il rentre ; Bertille donne les moufles d'Hélène (Bosse en tête : un grand dino à écarter du feu).
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_grelot.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee", "bertille_vue"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 31],
	[0.92, "lead", 4],
	[0.94, "item", ["piece", 450]],
	[0.96, "item", ["manteau_duvet", 1]],
	[0.98, "clock", 11],
	[1.00, "dlog", true],
	[1.02, "demo", true],
	[1.04, "no_help", null],
	[1.06, "auto", true],
	[1.08, "fast_battles", true],
	[1.38, "zone", &"monts"],
	[3.18, "calm", 900],
	[3.48, "calm", 900],
	[3.53, "tp", Vector2(58.6, 30.75)],
	[3.73, "wait_idle", [0.3, 60]],
	[3.83, "face", Vector2(0, -1)],
	[4.13, "interact_now", null],
	[5.33, "shot", "grelot_00_mur"],
	[6.53, "shot", "grelot_01_mur"],
	[7.73, "shot", "grelot_02_mur"],
	[8.93, "shot", "grelot_03_mur"],
	[10.13, "shot", "grelot_04_mur"],
	[11.33, "shot", "grelot_05_mur"],
	[12.53, "shot", "grelot_06_mur"],
	[13.73, "shot", "grelot_07_mur"],
	[13.93, "wait_idle", [2, 60]],
	[14.23, "shot", "grelot_08_parti"],
	[14.53, "calm", 900],
	[14.58, "tp", Vector2(22.5, 59.4)],
	[14.78, "wait_idle", [0.3, 60]],
	[14.88, "face", Vector2(0, -1)],
	[15.18, "interact_now", null],
	[16.48, "shot", "grelot_09_moufles"],
	[17.78, "shot", "grelot_10_moufles"],
	[19.08, "shot", "grelot_11_moufles"],
	[20.38, "shot", "grelot_12_moufles"],
	[21.68, "shot", "grelot_13_moufles"],
	[22.98, "shot", "grelot_14_moufles"],
	[23.18, "wait_idle", [2, 60]],
	[23.48, "shot", "grelot_15_fin"],
	[23.88, "state", null],
	[23.98, "party", null],
	[24.08, "tracker", null],
]
