extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): vérification pendant les répliques : Maïa assise dans la neige, sa mère, le masque ; (défi sauté) elles font équipe, les Cieux.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_maia_verif.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee", "bertille_vue", "glacier_arrivee", "mur_glace_1_brise", "mur_glace_2_brise", "grottes_glace_arrivee", "suie_monts_vue", "suie_monts_battue", "suie_monts_partie", "suie_indice", "dormeurs_reveilles", "blizzard_col", "roc_col_vu", "roc_innocente", "porte_givre_vue", "sanctuaire_givre_ouvert", "sanctuaire_givre_arrivee", "titan_parle", "titan_battu", "sceau_monts", "coeur_4", "found_journal_11"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 36],
	[0.92, "item", ["piece", 450]],
	[0.94, "item", ["manteau_duvet", 1]],
	[0.96, "item", ["masque_carton", 1]],
	[0.98, "clock", 11],
	[1.00, "dlog", true],
	[1.02, "demo", true],
	[1.04, "no_help", null],
	[1.06, "auto", false],
	[1.08, "fast_battles", true],
	[1.38, "zone", &"monts"],
	[3.18, "calm", 900],
	[3.48, "calm", 900],
	[3.53, "tp", Vector2(109.5, 13.45)],
	[3.73, "wait_idle", [0.3, 60]],
	[3.83, "face", Vector2(0, -1)],
	[4.13, "interact_now", null],
	[5.73, "shot", "maia_verif_00_retour"],
	[7.33, "press", "interact"],
	[8.93, "shot", "maia_verif_01_retour"],
	[10.53, "press", "interact"],
	[12.13, "shot", "maia_verif_02_retour"],
	[13.73, "press", "interact"],
	[15.33, "shot", "maia_verif_03_retour"],
	[16.93, "press", "interact"],
	[18.53, "shot", "maia_verif_04_retour"],
	[20.13, "press", "interact"],
	[21.73, "shot", "maia_verif_05_retour"],
	[23.33, "press", "interact"],
	[24.93, "shot", "maia_verif_06_retour"],
	[26.53, "press", "interact"],
	[28.13, "shot", "maia_verif_07_retour"],
	[29.73, "press", "interact"],
	[31.33, "shot", "maia_verif_08_retour"],
	[32.93, "press", "interact"],
	[34.53, "shot", "maia_verif_09_retour"],
	[36.13, "press", "interact"],
	[37.73, "shot", "maia_verif_10_retour"],
	[39.33, "press", "interact"],
	[40.93, "shot", "maia_verif_11_retour"],
	[42.53, "press", "interact"],
	[44.13, "shot", "maia_verif_12_retour"],
	[45.73, "press", "interact"],
	[47.33, "shot", "maia_verif_13_retour"],
	[48.93, "press", "interact"],
	[50.53, "shot", "maia_verif_14_retour"],
	[52.13, "press", "interact"],
	[53.73, "shot", "maia_verif_15_retour"],
	[55.33, "press", "interact"],
	[56.93, "shot", "maia_verif_16_retour"],
	[58.53, "press", "interact"],
	[60.13, "shot", "maia_verif_17_retour"],
	[61.73, "press", "interact"],
	[63.33, "shot", "maia_verif_18_retour"],
	[64.93, "press", "interact"],
	[66.53, "shot", "maia_verif_19_retour"],
	[68.13, "press", "interact"],
	[69.73, "shot", "maia_verif_20_retour"],
	[71.33, "press", "interact"],
	[72.93, "shot", "maia_verif_21_retour"],
	[74.53, "press", "interact"],
	[76.13, "shot", "maia_verif_22_retour"],
	[77.73, "press", "interact"],
	[79.33, "shot", "maia_verif_23_retour"],
	[80.93, "press", "interact"],
	[80.98, "pick", 1],
	[82.58, "shot", "maia_verif_24_plus_tard"],
	[84.18, "press", "interact"],
	[84.48, "static", ["res://story/monts_fin.gd", "_beaten", "@MaiaMonts", "@CaillouMonts"]],
	[86.08, "shot", "maia_verif_25_equipe"],
	[87.68, "press", "interact"],
	[89.28, "shot", "maia_verif_26_equipe"],
	[90.88, "press", "interact"],
	[92.48, "shot", "maia_verif_27_equipe"],
	[94.08, "press", "interact"],
	[95.68, "shot", "maia_verif_28_equipe"],
	[97.28, "press", "interact"],
	[98.88, "shot", "maia_verif_29_equipe"],
	[100.48, "press", "interact"],
	[102.08, "shot", "maia_verif_30_equipe"],
	[103.68, "press", "interact"],
	[105.28, "shot", "maia_verif_31_equipe"],
	[106.88, "press", "interact"],
	[108.48, "shot", "maia_verif_32_equipe"],
	[110.08, "press", "interact"],
	[111.68, "shot", "maia_verif_33_equipe"],
	[113.28, "press", "interact"],
	[114.88, "shot", "maia_verif_34_equipe"],
	[116.48, "press", "interact"],
	[118.08, "shot", "maia_verif_35_equipe"],
	[119.68, "press", "interact"],
	[121.28, "shot", "maia_verif_36_equipe"],
	[122.88, "press", "interact"],
	[124.48, "shot", "maia_verif_37_equipe"],
	[126.08, "press", "interact"],
	[127.68, "shot", "maia_verif_38_equipe"],
	[129.28, "press", "interact"],
	[130.88, "shot", "maia_verif_39_equipe"],
	[132.48, "press", "interact"],
	[134.08, "shot", "maia_verif_40_equipe"],
	[135.68, "press", "interact"],
	[137.28, "shot", "maia_verif_41_equipe"],
	[138.88, "press", "interact"],
	[140.48, "shot", "maia_verif_42_equipe"],
	[142.08, "press", "interact"],
	[143.68, "shot", "maia_verif_43_equipe"],
	[145.28, "press", "interact"],
	[146.88, "shot", "maia_verif_44_equipe"],
	[148.48, "press", "interact"],
	[148.88, "state", null],
	[148.98, "party", null],
	[149.08, "tracker", null],
]
