extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): le sanctuaire de Givre : le Titan descend de la cascade, le combat d'honneur, l'autel, le Sceau et le 4e Cœur.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_titan.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee", "bertille_vue", "glacier_arrivee", "mur_glace_1_brise", "mur_glace_2_brise", "grottes_glace_arrivee", "suie_monts_vue", "suie_monts_battue", "suie_monts_partie", "suie_indice", "dormeurs_reveilles", "blizzard_col", "roc_col_vu", "roc_innocente", "porte_givre_vue", "sanctuaire_givre_ouvert"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 35],
	[0.92, "item", ["piece", 450]],
	[0.94, "item", ["manteau_duvet", 1]],
	[0.96, "clock", 11],
	[0.98, "dlog", true],
	[1.00, "demo", true],
	[1.02, "no_help", null],
	[1.04, "auto", true],
	[1.06, "fast_battles", true],
	[1.36, "zone", &"sanctuaire_givre"],
	[3.16, "calm", 900],
	[4.46, "shot", "titan_00_arrivee"],
	[5.76, "shot", "titan_01_arrivee"],
	[7.06, "shot", "titan_02_arrivee"],
	[8.36, "shot", "titan_03_arrivee"],
	[9.66, "shot", "titan_04_arrivee"],
	[10.96, "shot", "titan_05_arrivee"],
	[11.16, "wait_idle", [2, 60]],
	[11.46, "calm", 900],
	[11.51, "tp", Vector2(16, 12.5)],
	[11.71, "wait_idle", [0.3, 60]],
	[11.81, "face", Vector2(0, -1)],
	[12.11, "interact_now", null],
	[13.61, "shot", "titan_06_titan"],
	[15.11, "shot", "titan_07_titan"],
	[16.61, "shot", "titan_08_titan"],
	[18.11, "shot", "titan_09_titan"],
	[19.61, "shot", "titan_10_titan"],
	[21.11, "shot", "titan_11_titan"],
	[22.61, "shot", "titan_12_titan"],
	[24.11, "shot", "titan_13_titan"],
	[25.61, "shot", "titan_14_titan"],
	[27.11, "shot", "titan_15_titan"],
	[27.31, "wait_idle", [3, 240]],
	[27.61, "shot", "titan_16_fin"],
	[28.01, "state", null],
	[28.11, "party", null],
	[28.21, "tracker", null],
]
