extends RefCounted
## Chapter 6, one moment of the chapter (state set by flags, then only this moment; histoire agent,
## scratchpad ch6/histoire/gen_scenarios.mjs): le glacier (traces, fiole, mur qui a repoussé), puis la première nuit (les forges, la page 30).
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/ch6_glacier.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif", "recif_arrivee", "mosasaure_parle", "mosasaure_battu", "sceau_cote", "coeur_3", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "moustique_vu", "maia_guet_vue", "found_journal_23", "maia_enfuie", "masque_carton", "roc_isaure", "roc_sceau_cote", "roc_carte_intacte", "monts_ouverts", "monts_arrivee", "bertille_vue"]],
	[0.82, "give_named", ["parasaurolophus", "Écho", 6]],
	[0.84, "give_named", ["plesiosaurus", "Nessie", 6]],
	[0.86, "give_named", ["baryonyx", "Bouée", 6]],
	[0.88, "give_named", ["pachyrhinosaurus", "Bosse", 6]],
	[0.90, "level", 31],
	[0.92, "item", ["piece", 450]],
	[0.94, "item", ["manteau_duvet", 1]],
	[0.96, "clock", 11],
	[0.98, "dlog", true],
	[1.00, "demo", true],
	[1.02, "no_help", null],
	[1.04, "auto", true],
	[1.06, "fast_battles", true],
	[1.36, "zone", &"monts"],
	[3.16, "calm", 900],
	[3.46, "calm", 900],
	[3.51, "tp", Vector2(46, 37)],
	[3.71, "wait_idle", [0.3, 60]],
	[3.91, "hold", "move_up"],
	[4.51, "hold", ""],
	[5.71, "shot", "glacier_00_glacier"],
	[6.91, "shot", "glacier_01_glacier"],
	[8.11, "shot", "glacier_02_glacier"],
	[9.31, "shot", "glacier_03_glacier"],
	[10.51, "shot", "glacier_04_glacier"],
	[11.71, "shot", "glacier_05_glacier"],
	[12.91, "shot", "glacier_06_glacier"],
	[14.11, "shot", "glacier_07_glacier"],
	[14.31, "wait_idle", [2, 60]],
	[14.61, "shot", "glacier_08_fin_glacier"],
	[14.91, "clock", 20.9],
	[18.91, "state", null],
	[20.11, "shot", "glacier_09_nuit"],
	[21.31, "shot", "glacier_10_nuit"],
	[22.51, "shot", "glacier_11_nuit"],
	[23.71, "shot", "glacier_12_nuit"],
	[24.91, "shot", "glacier_13_nuit"],
	[26.11, "shot", "glacier_14_nuit"],
	[26.31, "wait_idle", [2, 60]],
	[26.61, "shot", "glacier_15_fin_nuit"],
	[27.01, "state", null],
	[27.11, "party", null],
	[27.21, "tracker", null],
]
