extends RefCounted
## The little life of a kind of place (Wildlife, WildlifeDB): the caves: glow-worms on the rims of the walls, drops falling, nothing flying; crabs in the sea caves.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/faune_grotte.gd

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue", "joss_cote_vu", "filet_coupe", "nessie", "masque_plongee", "barque_nuit_vue", "grottes_arrivee", "cache_vue", "passeur_parle", "passeur_battu", "passeur_parti", "caisses_fouillees", "barque_isaure_vue", "found_journal_21", "passe_recif"]],
	[0.82, "clock", 11.0], [0.84, "weather", &"clear"], [0.86, "talk", true], [0.87, "vsync", false],
	[1.0, "zone", &"grottes_marines"], [2.0, "calm", 900.0], [2.3, "calm", 900.0], [2.6, "calm", 900.0], [2.9, "calm", 900.0], [3.2, "calm", 900.0], [3.6, "calm", 900.0], [4.0, "calm", 900.0],
	[5.5, "shot", "gr_marine_a"], [6.1, "shot", "gr_marine_b"], [6.2, "perf", "grottes_marines"],
	[6.3, "zone", &"grotte_echos"], [7.3, "calm", 900.0], [7.6, "calm", 900.0], [7.9, "calm", 900.0], [8.2, "calm", 900.0], [8.5, "calm", 900.0], [8.9, "calm", 900.0], [9.3, "calm", 900.0],
	[10.5, "shot", "gr_echos_a"], [11.1, "shot", "gr_echos_b"], [11.2, "perf", "grotte_echos"],
]
