extends RefCounted
## Names of the dinos (ch. 1-5 audit): Écho (the starter) in the party but NOT the lead (a
## Triceratops « Cornu » leads). The Marais's arrival (Écho answers the Voix: brought out as a
## stand-in « EchoScene »), then the Voix's lines VOIX_AGAIN_ECHO 0, 1, 2 (Écho out for each).
## godot --path Godot --script res://tools/capture.gd -- out=<scratchpad>/ch6/noms/marais scenario_file=res://tools/scenarios/noms_marais.gd rush=1

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "oeuf_vole_apaise", "cage_ouverte", "sceau_foret", "cages_ouvertes", "found_journal_11", "papiers_brac_lus", "masque_en_vue", "masque_vu", "maia_pont_vue", "maia_defi_2", "roc_oeuf_retrouve", "roc_sceau_foret", "tiroir_flaire", "ambre_noir_tiroir", "found_journal_3", "found_journal_4", "found_journal_10", "joss_marais_vu", "baryonyx_gilet_vu", "baryonyx_lecon", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "voix_echo_reconnu", "found_journal_ancien_voix", "temple_ouvert"]],
	[0.82, "starter", "parasaurolophus"],
	[0.84, "give_named", ["triceratops", "Cornu", 20]],
	[0.86, "lead", 1],
	[0.88, "level", 20],
	[0.90, "clock", 11],
	[0.92, "weather", &"clear"],
	[0.94, "dlog", true],
	[0.96, "demo", true],
	[0.98, "no_help", null],
	[1.00, "auto", true],
	[1.02, "party", null],
	[1.30, "zone", &"marais"],
	[3.00, "nodes", "EchoScene"],
	[3.30, "nodes", "EchoScene"],
	[3.60, "nodes", "EchoScene"],
	[3.90, "nodes", "EchoScene"],
	[4.20, "nodes", "EchoScene"],
	[4.50, "nodes", "EchoScene"],
	[4.80, "nodes", "EchoScene"],
	[5.10, "nodes", "EchoScene"],
	[5.40, "nodes", "EchoScene"],
	[5.70, "nodes", "EchoScene"],
	[6.00, "nodes", "EchoScene"],
	[6.30, "nodes", "EchoScene"],
	[6.60, "nodes", "EchoScene"],
	[6.90, "nodes", "EchoScene"],
	[7.20, "nodes", "EchoScene"],
	[7.50, "nodes", "EchoScene"],
	[7.80, "nodes", "EchoScene"],
	[8.10, "nodes", "EchoScene"],
	[8.40, "nodes", "EchoScene"],
	[8.70, "nodes", "EchoScene"],
	[9.00, "nodes", "EchoScene"],
	[9.30, "nodes", "EchoScene"],
	[9.60, "nodes", "EchoScene"],
	[9.90, "nodes", "EchoScene"],
	[10.20, "nodes", "EchoScene"],
	[10.50, "nodes", "EchoScene"],
	[10.80, "nodes", "EchoScene"],
	[11.10, "nodes", "EchoScene"],
	[11.40, "nodes", "EchoScene"],
	[11.70, "nodes", "EchoScene"],
	[12.00, "nodes", "EchoScene"],
	[12.30, "nodes", "EchoScene"],
	[12.60, "nodes", "EchoScene"],
	[12.90, "nodes", "EchoScene"],
	[13.20, "nodes", "EchoScene"],
	[13.50, "nodes", "EchoScene"],
	[13.80, "nodes", "EchoScene"],
	[14.10, "nodes", "EchoScene"],
	[14.40, "nodes", "EchoScene"],
	[14.70, "nodes", "EchoScene"],
	[15.00, "nodes", "EchoScene"],
	[15.30, "nodes", "EchoScene"],
	[15.60, "nodes", "EchoScene"],
	[15.90, "nodes", "EchoScene"],
	[16.20, "nodes", "EchoScene"],
	[16.50, "nodes", "EchoScene"],
	[16.80, "nodes", "EchoScene"],
	[17.10, "nodes", "EchoScene"],
	[17.40, "nodes", "EchoScene"],
	[17.70, "nodes", "EchoScene"],
	[18.00, "nodes", "EchoScene"],
	[18.30, "nodes", "EchoScene"],
	[18.60, "nodes", "EchoScene"],
	[18.90, "nodes", "EchoScene"],
	[19.20, "nodes", "EchoScene"],
	[19.50, "nodes", "EchoScene"],
	[19.80, "nodes", "EchoScene"],
	[20.10, "nodes", "EchoScene"],
	[20.40, "nodes", "EchoScene"],
	[20.70, "nodes", "EchoScene"],
	[21.00, "nodes", "EchoScene"],
	[21.30, "nodes", "EchoScene"],
	[21.60, "nodes", "EchoScene"],
	[21.90, "nodes", "EchoScene"],
	[22.20, "nodes", "EchoScene"],
	[22.50, "nodes", "EchoScene"],
	[22.80, "nodes", "EchoScene"],
	[23.10, "nodes", "EchoScene"],
	[23.40, "nodes", "EchoScene"],
	[23.70, "nodes", "EchoScene"],
	[24.00, "nodes", "EchoScene"],
	[24.30, "nodes", "EchoScene"],
	[24.60, "nodes", "EchoScene"],
	[24.90, "nodes", "EchoScene"],
	[25.20, "nodes", "EchoScene"],
	[25.50, "nodes", "EchoScene"],
	[25.80, "nodes", "EchoScene"],
	[27.00, "wait_idle", [1.0, 60]],
	[27.10, "nodes", "EchoScene"],
	[27.20, "calm", 900.0],
	[27.30, "tp", Vector2(57.3, 38.4)],
	[27.50, "hold", "move_left"],
	[27.62, "hold", ""],
	[28.00, "interact_now", null],
	[28.40, "nodes", "EchoScene"],
	[28.50, "shot", "ma_voix_0"],
	[28.60, "wait_idle", [1.0, 30]],
	[28.70, "nodes", "EchoScene"],
	[29.00, "interact_now", null],
	[29.40, "nodes", "EchoScene"],
	[29.50, "shot", "ma_voix_1"],
	[29.60, "wait_idle", [1.0, 30]],
	[29.70, "nodes", "EchoScene"],
	[30.00, "interact_now", null],
	[30.40, "nodes", "EchoScene"],
	[30.50, "shot", "ma_voix_2"],
	[30.60, "wait_idle", [1.0, 30]],
	[30.70, "nodes", "EchoScene"],
	[31.00, "party", null],
]
