extends RefCounted
## Check (30/09): the second half of the goat's story, on its own — Brac is already beaten, so
## the camp has only the chewed rope left (the trigger by the stake), and at Havre-Doré Bardane
## is home in Pervenche's lane and Pervenche thanks Chloé with berries.
## The camp's own lines are let run first (presses), then Chloé walks into the stake's circle.
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/test_chevre_fin.gd

const H := "res://tools/scenarios/chevre_outils.gd"
const STEPS := [
	[0.8, "flags", ["selle", "sceau_plaines", "havre_arrive", "vu_herboristerie", "foret_arrivee",
		"mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu",
		"sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "chevre_volee_dite", "chevre_vue",
		"brac_battu", "oeuf_vole_apaise", "cage_ouverte", "utah_lecon", "sceau_foret",
		"cages_ouvertes", "papiers_brac_lus", "griffe_grise_vu", "clairiere_vue"]],
	[0.9, "calm", 900.0], [1.0, "clock", 11.0], [1.1, "dlog", true], [1.12, "no_help", null],
	[1.2, "zone", &"camp_ombre"],
	# let the camp say whatever it says on coming back
	[4.00, "press", "interact"],
	[5.10, "press", "interact"],
	[6.20, "press", "interact"],
	[7.30, "press", "interact"],
	[8.40, "press", "interact"],
	[9.50, "press", "interact"],
	[10.60, "press", "interact"],
	[11.70, "press", "interact"],
	[12.80, "press", "interact"],
	[13.90, "press", "interact"],
	[16.0, "static", [H, "here"]], [16.4, "static", [H, "report"]],
	# walk into the circle by the stake: the rope is chewed, and Bardane is gone
	[16.8, "tp", Vector2(28.0, 18.8)], [17.0, "hold", "move_up"], [18.8, "hold", ""],
	[19.8, "shot", "f1_corde_rongee"],
	[20.40, "press", "interact"],
	[21.50, "press", "interact"],
	[22.60, "press", "interact"],
	[23.70, "press", "interact"],
	[24.80, "press", "interact"],
	[25.90, "press", "interact"],
	[27.00, "press", "interact"],
	[28.10, "press", "interact"],
	[29.20, "press", "interact"],
	[30.30, "press", "interact"],
	[31.40, "press", "interact"],
	[32.50, "press", "interact"],
	[34.0, "shot", "f2_sabots"], [34.4, "static", [H, "report"]],
	# Havre-Doré: home in the lane, and Pervenche thanks her
	[34.8, "zone", &"havre_dore"],
	[37.50, "press", "interact"],
	[38.60, "press", "interact"],
	[39.70, "press", "interact"],
	[40.80, "press", "interact"],
	[41.90, "press", "interact"],
	[43.00, "press", "interact"],
	[45.0, "static", [H, "here"]], [45.2, "tp", Vector2(12.2, 7.6)], [45.4, "face", Vector2(-1, 0)],
	[46.2, "shot", "f3_rentree"],
	[46.6, "tp", Vector2(9.6, 12.0)], [46.8, "face", Vector2(0, -1)], [47.2, "static", [H, "pervenche"]],
	[48.4, "shot", "f4_merci"],
	[49.00, "press", "interact"],
	[50.10, "press", "interact"],
	[51.20, "press", "interact"],
	[52.30, "press", "interact"],
	[53.40, "press", "interact"],
	[54.50, "press", "interact"],
	[55.60, "press", "interact"],
	[56.70, "press", "interact"],
	[57.80, "press", "interact"],
	[58.90, "press", "interact"],
	[60.00, "press", "interact"],
	[61.10, "press", "interact"],
	[62.20, "press", "interact"],
	[63.30, "press", "interact"],
	[64.40, "press", "interact"],
	[65.50, "press", "interact"],
	[66.60, "press", "interact"],
	[67.70, "press", "interact"],
	[68.80, "press", "interact"],
	[69.90, "press", "interact"],
	[71.00, "press", "interact"],
	[72.10, "press", "interact"],
	[73.20, "press", "interact"],
	[74.30, "press", "interact"],
	[75.40, "press", "interact"],
	[76.50, "press", "interact"],
	[78.5, "shot", "f5_baies"], [79.0, "static", [H, "report"]], [79.5, "state", null],
]
