extends RefCounted
## Variantes de personnages (Stage.dress, Stage.pose): the lagoon scene of chapter 5 (story/cote_lagon.gd)
## from its start: Joss comes out of the water backwards with his jar on his head (joss_bocal.png), then,
## by the net, Chloé kneels (CoteStage.kneel: her crouching picture). The scene plays itself (auto).
## godot --path Godot --script res://tools/capture.gd -- out=<dossier> scenario_file=res://tools/scenarios/variantes_joss.gd

const STEPS := [
	[0.80, "flags", ["sceau_plaines", "maia_defi_1", "found_journal_6", "havre_arrive", "selle", "barque_vue", "foret_arrivee", "griffe_grise_vu", "clairiere_vue", "found_journal_ancien", "mur_camp_brise", "camp_arrive", "sbire_camp_1_vu", "sbire_camp_2_vu", "sbire_camp_1_battu", "sbire_camp_2_battu", "brac_parle", "brac_battu", "cage_ouverte", "sceau_foret", "found_journal_11", "papiers_brac_lus", "masque_vu", "maia_defi_2", "ambre_noir_tiroir", "marais_arrivee", "joss_marais_vu", "gilet_nage", "porte_voix_ouverte", "voix_rencontree", "temple_ouvert", "dame_suie_battue", "temple_vanne_1", "temple_vanne_2", "temple_vanne_3", "spinosaure_battu", "sceau_marais", "coeur_1", "found_journal_12", "found_journal_13", "found_journal_14", "found_journal_15", "found_journal_16", "roc_marais_vu", "maia_defi_3", "desert_arrivee", "sirocco_vue", "fossile_1", "fossile_2", "fossile_3", "fossile_4", "fossile_5", "fossiles_rendus", "rempart_ouvert", "rempart_rencontre", "found_journal_17", "found_journal_20", "brac_desert_vu", "brac_desert_battu", "chariot_fouille", "carnotaurus_apaise", "sanctuaire_ouvert", "sceau_desert", "sanctuaire_entre", "coeur_2", "maia_oasis_vue", "maia_defi_4", "met_roc", "lunettes_trouvees", "lunettes_rendues", "larmes_expliquees", "roc_sceau_foret", "roc_sceau_marais", "roc_sceau_desert", "cote_annonce", "cote_ouverte", "cote_arrivee", "pecheurs_vus", "maia_falaises_vue"]],
	[0.82, "give", "baryonyx"],
	[0.88, "level", 27],
	[0.90, "clock", 11],
	[0.92, "weather", &"clear"],
	[0.94, "dlog", true],
	[1.00, "auto", true],
	[1.30, "zone", &"cote"],
	[3.10, "calm", 900],
	[3.12, "camera_distance", 8.0],
	[3.42, "tp", Vector2(60, 57.95)],
	[3.72, "hold", "move_up"],
	[3.82, "hold", ""],
	[4.12, "interact_now", null],
	[5.00, "shot", "vj_00"],
	[6.25, "shot", "vj_01"],
	[7.50, "shot", "vj_02"],
	[8.75, "shot", "vj_03"],
	[10.00, "shot", "vj_04"],
	[11.25, "shot", "vj_05"],
	[12.50, "shot", "vj_06"],
	[13.75, "shot", "vj_07"],
	[15.00, "shot", "vj_08"],
	[16.25, "shot", "vj_09"],
	[17.50, "shot", "vj_10"],
	[18.75, "shot", "vj_11"],
	[20.00, "shot", "vj_12"],
	[21.25, "shot", "vj_13"],
	[22.50, "shot", "vj_14"],
	[23.75, "shot", "vj_15"],
	[25.00, "shot", "vj_16"],
	[26.25, "shot", "vj_17"],
	[27.50, "shot", "vj_18"],
	[28.75, "shot", "vj_19"],
	[30.00, "shot", "vj_20"],
	[31.25, "shot", "vj_21"],
	[32.50, "shot", "vj_22"],
	[33.75, "shot", "vj_23"],
]
