extends SceneTree
## Writes data/dex_places.gd: where each species lives, read from the zone scenes the game
## loads (their Habitat nodes and Encounters), so that the Dinodex's hints never drift from
## the game. tools/build_zone.gd runs it after building a zone; by hand:
##   godot --headless --path Godot --script res://tools/gen_dex.gd
## (Scripts are loaded at run time: the game's classes need the autoloads, which a --script
## main loop only gets after it is compiled.)

const OUT := "res://data/dex_places.gd"
## Test zones, not part of the island.
const SKIP := [&"clos_blanc"]


func _initialize() -> void:
	var result := write()
	print(result)
	quit(0 if result.begins_with("Dinodex") else 1)


## Reads every zone of world.gd ZONES and writes OUT. Returns what it did (or the error).
static func write() -> String:
	var zones: Dictionary = (load("res://world/world.gd") as GDScript).get_script_constant_map()["ZONES"]
	var region_script: GDScript = load("res://world/region.gd")
	var zone_rows: Array[String] = []
	var by_species := {}   # species id -> Array of rows (String)
	var count := 0
	for id: StringName in zones:
		if id in SKIP:
			continue
		var r: Node = region_script.call("open_for_preview", zones[id])
		if r == null:
			return "Zone illisible : %s" % zones[id]
		var size: Vector2i = r.call("map_size")
		var zone_label: String = r.get("zone_name") if String(r.get("zone_name")) != "" else r.get("display_name")
		zone_rows.append('\t&"%s": {"name": "%s", "size": Vector2i(%d, %d), "indoor": %s},' % [id, _esc(zone_label), size.x, size.y,
			"true" if r.get("indoor") else "false"])
		for h: Node in r.call("habitats"):
			var area := Rect2(h.get("position") / 48.0, h.get("size") / 48.0)
			for e: Resource in h.get("encounters"):
				if e == null:
					continue
				var sp: StringName = e.get("species")
				var weathers: Array = Array(e.get("weathers")).map(func(w: StringName) -> String: return '&"%s"' % w)
				var levels: Vector2i = e.get("levels")
				var row := '{"zone": &"%s", "place": "%s", "area": Rect2(%s, %s, %s, %s), "levels": Vector2i(%d, %d), "when": %d, "hidden": %s, "weathers": [%s], "weight": %d}' % [
					id, _esc(h.get("label")), _num(area.position.x), _num(area.position.y), _num(area.size.x), _num(area.size.y),
					levels.x, levels.y, e.get("when"), "true" if e.get("hidden") else "false", ", ".join(weathers), e.get("weight")]
				if not by_species.has(sp):
					by_species[sp] = []
				by_species[sp].append(row)
				count += 1
		r.free()
	var lines: Array[String] = [
		"class_name DexPlaces",
		"## GENERATED by tools/gen_dex.gd from the zone scenes' habitats: do not edit. It runs again",
		"## after each zone built by tools/build_zone.gd; by hand (a zone scene edited in Godot):",
		"##   godot --headless --path Godot --script res://tools/gen_dex.gd",
		"## ZONES: each zone's name, size (tiles), indoor. SPECIES: species id -> where it lives, one",
		"## row per Encounter of a Habitat: zone, place (the habitat's label), area (tiles), levels,",
		"## when (Encounter.when: 0 toujours, 1 jour, 2 nuit, 3 aube et crépuscule, 4 jour et",
		"## crépuscule, 5 pleine lune), hidden (in the tall grass) or roaming in sight, weathers.",
		"",
		"const ZONES := {",
	]
	lines.append_array(zone_rows)
	lines.append("}")
	lines.append("")
	lines.append("const SPECIES := {")
	var ids := by_species.keys()
	ids.sort_custom(func(a: StringName, b: StringName) -> bool: return String(a) < String(b))
	for sp: StringName in ids:
		lines.append('\t&"%s": [' % sp)
		for row: String in by_species[sp]:
			lines.append("\t\t%s," % row)
		lines.append("\t],")
	lines.append("}")
	var f := FileAccess.open(OUT, FileAccess.WRITE)
	if f == null:
		return "Écriture impossible : %s" % OUT
	f.store_string("\n".join(lines) + "\n")
	f.close()
	return "Dinodex : %d rencontres de %d espèces dans %d zones -> %s" % [count, by_species.size(), zone_rows.size(), OUT]


static func _esc(s: String) -> String:
	return s.replace("\\", "\\\\").replace('"', '\\"')


static func _num(v: float) -> String:
	return str(snappedf(v, 0.01))
