class_name AtlasDB
## Generated by tools/maps/gen-atlas.mjs (do not edit: run it again). The regions of Ambrelune
## on its atlas (assets/art/ui/atlas_ile.png): name, zones of the game in it (the first one has
## the detailed map), levels of its wild dinos, where its name goes (0–1), its bounding box
## (0–1: the first zone's detailed map is laid over it, to place Chloé).
## atlas_regions.png holds each region's index * 16 (the sea: 255).

const REGIONS := [
	{"id": &"plaines", "name": "Plaines des Fougères", "zones": [&"plaines", &"grotte_echos", &"antre_crane"], "levels": Vector2i(2, 8), "label": Vector2(0.540, 0.686), "bounds": Rect2(0.422, 0.521, 0.227, 0.299)},
	{"id": &"port", "name": "Port-Ambre", "zones": [&"port_ambre", &"cabinet"], "levels": Vector2i(1, 1), "label": Vector2(0.493, 0.821), "bounds": Rect2(0.483, 0.778, 0.141, 0.080)},
	{"id": &"havre", "name": "Havre-Doré", "zones": [&"havre_dore"], "levels": Vector2i(1, 1), "label": Vector2(0.709, 0.737), "bounds": Rect2(0.644, 0.675, 0.075, 0.094)},
	{"id": &"foret", "name": "Forêt Jurassique", "zones": [&"foret"], "levels": Vector2i(10, 18), "label": Vector2(0.339, 0.627), "bounds": Rect2(0.146, 0.464, 0.342, 0.327)},
	{"id": &"marais", "name": "Marais Brumeux", "zones": [&"marais"], "levels": Vector2i(16, 24), "label": Vector2(0.235, 0.476), "bounds": Rect2(0.115, 0.368, 0.290, 0.239)},
	{"id": &"desert", "name": "Désert Aride", "zones": [&"desert"], "levels": Vector2i(22, 30), "label": Vector2(0.344, 0.305), "bounds": Rect2(0.156, 0.186, 0.349, 0.221)},
	{"id": &"cote", "name": "Côte Préhistorique", "zones": [&"cote"], "levels": Vector2i(28, 35), "label": Vector2(0.627, 0.257), "bounds": Rect2(0.459, 0.199, 0.369, 0.123)},
	{"id": &"monts", "name": "Monts Gelés", "zones": [&"monts"], "levels": Vector2i(33, 40), "label": Vector2(0.747, 0.479), "bounds": Rect2(0.593, 0.259, 0.334, 0.435)},
	{"id": &"cieux", "name": "Cieux Éternels", "zones": [&"cieux"], "levels": Vector2i(38, 44), "label": Vector2(0.585, 0.348), "bounds": Rect2(0.476, 0.262, 0.251, 0.184)},
	{"id": &"volcan", "name": "Plaine Volcanique", "zones": [&"volcan"], "levels": Vector2i(42, 48), "label": Vector2(0.500, 0.431), "bounds": Rect2(0.391, 0.362, 0.250, 0.253)},
	{"id": &"apex", "name": "Terre des Apex", "zones": [&"apex"], "levels": Vector2i(50, 50), "label": Vector2(0.500, 0.527), "bounds": Rect2(0.482, 0.423, 0.068, 0.091)},
]
## Places inside the regions, marked once visited: [zone, name, where (0–1)].
const PLACES := [
	[&"grotte_echos", "Grotte des Échos", Vector2(0.492, 0.608)],
	[&"antre_crane", "Grand Crâne", Vector2(0.562, 0.685)],
	[&"cabinet", "Cabinet", Vector2(0.508, 0.785)],
]
