class_name DexDB
## The Dinodex: every species in its order, numbered (#001…), the uniques of the story apart
## (DexFacts.UNIQUES); what Chloé knows of each one: not seen yet, seen (Game.dex_seen: met in
## a battle, or close by in the world), caught (Game.dex_caught: captured, given, hatched…);
## where each one lives, read from the zones' habitats (DexPlaces, generated by
## tools/gen_dex.gd), told as hints: only the region, as a rumour, before Chloé has seen it
## (and only a region she knows), every place with its moments once she has; the regions and
## their counts; the dinos Chloé has of a species (her party, the reserve).

const UNSEEN := &"unseen"
const SEEN := &"seen"
const CAUGHT := &"caught"

## The Dinodex's regions, in the island's order (AtlasDB region ids): the short name of their
## tab, how to say « in it ». Those without species yet get no tab.
const REGIONS := [
	{"id": &"plaines", "short": "Plaines", "in": "dans les Plaines des Fougères"},
	{"id": &"foret", "short": "Forêt", "in": "dans la Forêt Jurassique"},
	{"id": &"marais", "short": "Marais", "in": "dans le Marais Brumeux"},
	{"id": &"desert", "short": "Désert", "in": "dans le Désert Aride"},
	{"id": &"cote", "short": "Côte", "in": "sur la Côte Préhistorique"},
	{"id": &"monts", "short": "Monts", "in": "dans les Monts Gelés"},
	{"id": &"cieux", "short": "Cieux", "in": "dans les Cieux Éternels"},
	{"id": &"volcan", "short": "Volcan", "in": "dans la Plaine Volcanique"},
]
const FAMILY_NAMES := {
	&"raptor": "Raptor", &"tyrant": "Grand prédateur", &"spino": "Spinosauridé", &"ceratopsian": "Cératopsien",
	&"armored": "Cuirassé", &"hadrosaur": "Ornithopode", &"sauropod": "Sauropode", &"flyer": "Ptérosaure",
	&"marine": "Reptile marin",
}
const RARITY_NAMES := {"common": "Commune", "rare": "Rare", "epic": "Très rare", "legendary": "Légendaire"}
const PHASE_NAMES := {&"dawn": "à l'aube", &"day": "le jour", &"dusk": "au crépuscule", &"night": "la nuit"}
const WEATHER_NAMES := {&"clear": "par beau temps", &"rain": "sous la pluie", &"mist": "dans la brume",
	&"storm": "pendant l'orage", &"sandstorm": "dans la tempête de sable", &"snow": "quand il neige",
	&"blizzard": "dans le blizzard"}
## The ones who pass the word around (a species keeps the same voice: the Dinodex does not
## change each time it opens, but neighbours sound different). {lieu}: where.
const VOICES := [
	"On dit qu'on en croise {lieu}.",
	"Un vieux pêcheur de Port-Ambre jure en avoir vu un {lieu}.",
	"D'après les promeneurs, il faudrait chercher {lieu}.",
	"Maïa prétend en avoir suivi la trace {lieu}.",
	"On raconte au village qu'il vit {lieu}.",
	"Le Pr Roc a entendu dire qu'il se cache {lieu}.",
	"Hélène a noté dans son carnet : « vu {lieu} ».",
]
## Hélène's three eggs (Game.STARTERS): one of each waits at the Cabinet at the start.
const STARTER_HINT := "Hélène avait laissé un œuf de cette espèce au Cabinet de Port-Ambre."
const NOBODY := "Personne n'en a encore parlé… Explore l'île, et tu finiras bien par tomber dessus !"
## A place of a region Chloé has not been to yet: not named.
const ELSEWHERE := "Il vit aussi ailleurs, dans une région où tu n'es pas encore allée…"

static var _order: Array[StringName] = []


# ------------------------------------------------------------------ the list

## The species of the Dinodex (not the uniques), in their order: SpeciesDB's (region by region).
static func order() -> Array[StringName]:
	if _order.is_empty():
		for id: StringName in SpeciesDB.all_ids():
			if not is_unique(id):
				_order.append(id)
	return _order


static func uniques() -> Array[StringName]:
	var out: Array[StringName] = []
	for u: Dictionary in DexFacts.UNIQUES:
		if SpeciesDB.PATHS.has(u["id"]):
			out.append(u["id"])
	return out


static func is_unique(id: StringName) -> bool:
	return DexFacts.UNIQUES.any(func(u: Dictionary) -> bool: return u["id"] == id)


static func unique_info(id: StringName) -> Dictionary:
	for u: Dictionary in DexFacts.UNIQUES:
		if u["id"] == id:
			return u
	return {}


## « #007 », or « ★3 » for a unique.
static func number_text(id: StringName) -> String:
	var i := order().find(id)
	if i >= 0:
		return "#%03d" % (i + 1)
	return "★%d" % (uniques().find(id) + 1)


static func status(id: StringName) -> StringName:
	if Game.dex_caught.has(String(id)):
		return CAUGHT
	return SEEN if Game.dex_seen.has(String(id)) else UNSEEN


## [seen, caught] among `ids` (caught counts as seen).
static func counts(ids: Array) -> Vector2i:
	var n := Vector2i.ZERO
	for id: StringName in ids:
		var s := status(id)
		if s != UNSEEN:
			n.x += 1
		if s == CAUGHT:
			n.y += 1
	return n


# ------------------------------------------------------------------ regions

## The regions with species (REGIONS order): {id, name, short, in, zones, species, known}.
static func regions() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for r: Dictionary in REGIONS:
		var atlas := _atlas(r["id"])
		if atlas.is_empty():
			continue
		var ids: Array[StringName] = []
		for id in order():
			if region_ids_of(id).has(r["id"]):
				ids.append(id)
		if ids.is_empty():
			continue
		out.append({"id": r["id"], "name": atlas["name"], "short": r["short"], "in": r["in"], "zones": atlas["zones"],
			"species": ids, "known": region_known(r["id"])})
	return out


## The regions (AtlasDB ids) where `id` lives: its habitats' zones; a unique, its own.
static func region_ids_of(id: StringName) -> Array[StringName]:
	var out: Array[StringName] = []
	if is_unique(id):
		out.append(unique_info(id)["region"])
		return out
	for row: Dictionary in DexPlaces.SPECIES.get(id, []):
		var r := region_of_zone(row["zone"])
		if r != &"" and not out.has(r):
			out.append(r)
	return out


static func region_of_zone(zone: StringName) -> StringName:
	for r: Dictionary in AtlasDB.REGIONS:
		if zone in r["zones"]:
			return r["id"]
	return &""


## Chloé has been there (one of its zones is on her map, or she is in it, or the story says
## she went to its place without a map: IslandMap._place_visited).
static func region_known(region: StringName) -> bool:
	var atlas := _atlas(region)
	for z: StringName in atlas.get("zones", []):
		if z == Game.region_id or Game.explored.has(String(z)) or IslandMap._place_visited(z):
			return true
	return false


static func region_name(region: StringName) -> String:
	return _atlas(region).get("name", "")


static func _atlas(region: StringName) -> Dictionary:
	for r: Dictionary in AtlasDB.REGIONS:
		if r["id"] == region:
			return r
	return {}


static func _region_in(region: StringName) -> String:
	for r: Dictionary in REGIONS:
		if r["id"] == region:
			return r["in"]
	return "quelque part sur l'île"


# ------------------------------------------------------------------ where it lives

## Where `id` lives, one entry per place (a zone's habitat), its encounters put together:
## {zone, zone_name, region, place, where (« au nord-est »), phases (dawn, day, dusk, night),
## full_moon, hidden (in the tall grass), roaming (in sight), weathers ([]: any), levels}.
static func places(id: StringName) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	var by_key := {}
	for row: Dictionary in DexPlaces.SPECIES.get(id, []):
		var key := "%s/%s" % [row["zone"], row["place"]]
		if not by_key.has(key):
			var zone: Dictionary = DexPlaces.ZONES.get(row["zone"], {})
			by_key[key] = {"zone": row["zone"], "zone_name": zone.get("name", String(row["zone"])),
				"region": region_of_zone(row["zone"]), "place": row["place"], "where": _direction(row["zone"], row["area"]),
				"phases": [], "full_moon": false, "hidden": false, "roaming": false, "weathers": [], "any_weather": false,
				"levels": row["levels"]}
			out.append(by_key[key])
		var p: Dictionary = by_key[key]
		if row["when"] == Encounter.FULL_MOON:
			p["full_moon"] = true
		else:
			for ph: StringName in Encounter.PHASES[row["when"]]:
				if not ph in p["phases"]:
					p["phases"].append(ph)
		p["hidden" if row["hidden"] else "roaming"] = true
		if row["weathers"].is_empty():
			p["any_weather"] = true
		for w: StringName in row["weathers"]:
			if not w in p["weathers"]:
				p["weathers"].append(w)
		p["levels"] = Vector2i(mini(p["levels"].x, row["levels"].x), maxi(p["levels"].y, row["levels"].y))
	for p in out:
		if p["any_weather"]:
			p["weathers"] = []
	return out


## « le jour et au crépuscule », « à toute heure », « les nuits de pleine lune ».
static func moments_text(p: Dictionary) -> String:
	var parts: Array[String] = []
	var phases: Array = p["phases"]
	if phases.size() >= 4:
		parts.append("à toute heure")
	else:
		for ph: StringName in [&"dawn", &"day", &"dusk", &"night"]:
			if ph in phases:
				parts.append(PHASE_NAMES[ph])
	if p["full_moon"] and not &"night" in phases:
		parts.append("les nuits de pleine lune")
	return _join(parts)


## Habitats out on the water (where « hidden » means among the seaweed, not in the tall grass).
const SEA_PLACES: Array[String] = ["Le Large", "La Passe", "Le Lagon", "La Baie des Tortues"]


static func _is_sea(p: Dictionary) -> bool:
	return String(p["place"]) in SEA_PLACES or p["zone"] == &"recif_sanctuaire"


## Where a hidden one hides: in the seaweed at sea, the powder snow of the Monts, the tall grass.
static func hide_text(p: Dictionary) -> String:
	if _is_sea(p):
		return "dans les algues"
	if p["zone"] in [&"monts", &"grottes_glace", &"sanctuaire_givre"]:
		return "dans la neige poudreuse"
	return "dans les hautes herbes"


## How it is met there: roaming in sight, hidden (tall grass, seaweed, snow), or both.
static func how_text(p: Dictionary) -> String:
	if p["hidden"] and p["roaming"]:
		return "à découvert, ou caché " + hide_text(p)
	return ("caché " + hide_text(p)) if p["hidden"] else ("nage à découvert" if _is_sea(p) else "se promène à découvert")


## One place as a line: « le jour et au crépuscule · se promène à découvert · niv. 3 à 6 ».
static func place_details(p: Dictionary) -> String:
	var bits: Array[String] = [moments_text(p), how_text(p)]
	if not p["weathers"].is_empty():
		bits.append("seulement " + _join(p["weathers"].map(func(w: StringName) -> String: return WEATHER_NAMES.get(w, String(w)))))
	var lv: Vector2i = p["levels"]
	bits.append("niv. %d" % lv.x if lv.x == lv.y else "niv. %d à %d" % [lv.x, lv.y])
	return " · ".join(bits)


## The title of a place: « Plaines des Fougères — L'étang, à l'est ».
static func place_title(p: Dictionary) -> String:
	var where: String = p["where"]
	return "%s — %s%s" % [p["zone_name"], p["place"], ", " + where if where != "" else ""]


## Where the habitat is in its zone, seen from above (« au nord-est »); nothing indoors.
static func _direction(zone: StringName, area: Rect2) -> String:
	var z: Dictionary = DexPlaces.ZONES.get(zone, {})
	if z.is_empty() or z["indoor"]:
		return ""
	var c := area.get_center() / Vector2(z["size"]) - Vector2(0.5, 0.5)
	var ns := "nord" if c.y < -0.17 else "sud" if c.y > 0.17 else ""
	var ew := "ouest" if c.x < -0.17 else "est" if c.x > 0.17 else ""
	if ns == "" and ew == "":
		return "au centre"
	if ns != "" and ew != "":
		return "au %s-%s" % [ns, ew]
	return "au %s" % ns if ns != "" else "à l'%s" % ew


# ------------------------------------------------------------------ hints

## What the Dinodex says about where to find `id`. Not seen: a rumour naming only a region
## Chloé knows (else: nobody has said anything yet). Seen or caught: every place, precisely
## (see places, place_title, place_details), and for a unique, where she met it.
static func hints(id: StringName) -> Array[String]:
	var out: Array[String] = []
	var known := status(id) != UNSEEN
	if is_unique(id):
		var u := unique_info(id)
		if known:
			out.append(u["where"])
		else:
			out.append(u["rumour"] if region_known(u["region"]) else NOBODY)
		return out
	if known:
		var elsewhere := false
		for p in places(id):
			if region_known(p["region"]):
				out.append("%s : %s." % [place_title(p), place_details(p)])
			else:
				elsewhere = true
		if elsewhere:
			out.append(ELSEWHERE)
	else:
		var n := 0
		for r in region_ids_of(id):
			if region_known(r):
				out.append(rumour(id, "quelque part " + _region_in(r), n))
				n += 1
	if id in Game.STARTERS:
		out.append(STARTER_HINT)
	if out.is_empty():
		out.append(NOBODY)
	return out


## A rumour in the species' own voice (see VOICES).
static func rumour(id: StringName, where: String, n := 0) -> String:
	var i := posmod(SpeciesDB.all_ids().find(id) + n, VOICES.size())
	return String(VOICES[i]).replace("{lieu}", where)


# ------------------------------------------------------------------ what it is

## A dino of the species, grown, as a sample: its abilities, its attacks, its base stats.
static func sample(id: StringName) -> Dino:
	return Dino.create(id, Abilities.ADULT_LEVEL)


## The attacks the species learns, by level: [[level, move id], …].
static func learnset(id: StringName) -> Array:
	return MovesDB.learnset(sample(id))


static func type_of(id: StringName) -> String:
	return MovesDB.FAMILY_TYPES.get(SpeciesDB.get_species(id).family, "terre")


## Types it beats, types that beat it, types it resists (MovesDB.TYPE_CHART).
static func matchups(type: String) -> Dictionary:
	var strong: Array[String] = []
	var weak: Array[String] = []
	var resists: Array[String] = []
	for t: String in MovesDB.TYPE_CHART:
		if MovesDB.TYPE_CHART[type].get(t, 1.0) > 1.0:
			strong.append(t)
		var against: float = MovesDB.TYPE_CHART[t].get(type, 1.0)
		if against > 1.0:
			weak.append(t)
		elif against < 1.0:
			resists.append(t)
	return {"strong": strong, "weak": weak, "resists": resists}


static func facts(id: StringName) -> Dictionary:
	return DexFacts.INFO.get(id, {})


# ------------------------------------------------------------------ Roc's rewards

## What Roc gives at the Cabinet for the Dinodex (as in the web version): every ten species
## caught, each region whose species are all caught, the whole Dinodex. `gift`: said as is.
const MILESTONES := [
	{"at": 10, "items": {"collier": 5, "fougere": 2}, "gift": "5 colliers d'ambre et 2 fougères curatives"},
	{"at": 20, "items": {"collier": 8, "baie": 5}, "gift": "8 colliers d'ambre et 5 baies"},
	{"at": 30, "items": {"collier": 10, "fougere": 4, "piece": 150}, "gift": "10 colliers d'ambre, 4 fougères curatives et 150 pièces"},
]
const REGION_GIFT := {"items": {"fougere": 2, "piece": 100}, "gift": "2 fougères curatives et 100 pièces"}
const COMPLETE_GIFT := {"items": {"collier": 15, "fougere": 8, "piece": 400}, "gift": "15 colliers d'ambre, 8 fougères curatives et 400 pièces"}


## The rewards reached and not given yet: {flag (set once given), items, gift, text (Roc's)}.
static func pending_rewards() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	var caught := counts(order()).y
	for m: Dictionary in MILESTONES:
		if caught >= m["at"]:
			out.append(_reward(StringName("dex_palier_%d" % m["at"]), m,
				"Fais voir ton Dinodex… %d espèces ! Hélène n'en avait pas autant à ses débuts. Tiens, pour la suite." % m["at"]))
	for r in regions():
		if counts(r["species"]).y >= r["species"].size():
			out.append(_reward(StringName("dex_region_%s" % r["id"]), REGION_GIFT,
				"Toutes les espèces qui vivent %s sont dans ton Dinodex ! Voilà de quoi fêter ça." % r["in"]))
	if caught >= order().size():
		out.append(_reward(&"dex_complet", COMPLETE_GIFT, "Toutes les espèces de l'île… Tu as rempli le Dinodex ! Hélène n'y était jamais arrivée."))
	var pending: Array[Dictionary] = []
	for r in out:
		if not Game.flag(r["flag"]):
			pending.append(r)
	return pending


static func _reward(flag: StringName, def: Dictionary, text: String) -> Dictionary:
	return {"flag": flag, "items": def["items"], "gift": def["gift"], "text": text}


# ------------------------------------------------------------------ Chloé's own

## The dinos Chloé has of the species (its head's): {dino, in_party, index (in party or box)}.
static func owned(id: StringName) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for i in Game.party.size():
		if Game.party[i].species().id == id:
			out.append({"dino": Game.party[i], "in_party": true, "index": i})
	for i in Game.box.size():
		if Game.box[i].species().id == id:
			out.append({"dino": Game.box[i], "in_party": false, "index": i})
	return out


## When it was first seen / caught (« le 29 septembre »), or "".
static func date_text(unix: Variant) -> String:
	if unix == null or not (unix is int or unix is float):
		return ""
	const MONTHS := ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"]
	var d := Time.get_date_dict_from_unix_time(int(unix))
	return "le %d %s" % [d["day"], MONTHS[d["month"] - 1]]


## « a », « a et b », « a, b et c ».
static func _join(parts: Array) -> String:
	if parts.size() <= 1:
		return "" if parts.is_empty() else String(parts[0])
	return ", ".join(parts.slice(0, parts.size() - 1)) + " et " + String(parts.back())
